### ISSUE TITLE
How do we package refills?

### ISSUE THREAD

**Issue by teoljungberg** [thoughtbot/refills#227]
Right now, `refills` is packaged as a gem to be used as a `rails`-generator.
Which is not ideal since we exclude `refills` to be used along with frameworks
such as `middleman`, `sinatra`, or by other tools like `bower`. I would like us
to be compatible with all of the above.

My idea is that we extract out the `rails` part of refills and have it be just
the core HTML, CSS and JS. Then we build extensions for each framework, or
library. Then we can integrate deeper into how framework handles it's assets,
and provide better support for them. Maybe even have other maintainers of those
extensions?
That means that we would have extensions like: `refills-rails`,
`refills-middleman`, and so forth. Then each extension has a dependency upon
the core `refills` library, and before releasing you fetch the latest `refills`
and bundle that in.

Is this where we want `refills` to go, is it worth the effort?
Thoughts @tysongach, @Magnus-G?

**Comment by Magnus-G** [comment]
@teoljungberg theoretically is sounds like that makes sense. Practically I'm not the right person to ask! 
I guess my questions would be: Would there be any implications or large changes needed? Would the maintenance aspect of things grow as we add support?

Personally I don't use the gem at all so I'm not the target group here. And I wonder how many people actually are using the gem? Hard to know I guess.

**Comment by heaversm** [comment]
I would love to see this compatible with bower, and plan on trying to use it with middleman. As somewhat of a novice with tools like yeoman and bower, one issue I come across having traditionally just included libraries manually is that it's a bit difficult to know when to use a gem, when to use bower, and when to manually include scripts - and how to get them all to play nicely. Being able to stick to the method you began with (bower, yo, gems, etc) makes things seem a lot less daunting.

**Comment by teoljungberg** [comment]
We have ~12k downloads from rubygems, so there are people atleast using the project. It's uncertain to what extent though.

From a maintenance point-of-view - it would increase the burden. But I think that it would still be manageble, we want to make the integration between `refills-core` and the "plugins" as easy as possible for this to even be a possibility.

I'm still luke-warm to the idea, but I thought if would be good to raise the question and see what others think.

**Comment by tysongach** [comment]
The problem with Bower is that it doesn’t work well with files that are expected to change. This is exactly why we do not publish Bitters on Bower (we _do_ publish Bourbon and Neat on it).

Bower is great for vendor assets that are _not_ expected to change, e.g. jQuery or Normalize. But since we expect Refills and Bitters files to be tweaked and changed on a per-project basis, it’s not a good fit because Bower can easily update and overwrite those changes.

Personally, I’d rather see the website get updated to more easily browse Refills (too much scrolling right now, and the nav list is hidden) and more easily copy code. The gem is great, but I don’t think it’s mentioned at all on the website and we should be better about explaining how to use that.

**Comment by toobulkeh** [comment]
:+1: for middleman support. I'd be happy to help.

**Comment by teoljungberg** [comment]
@toobulkeh that would be fantastic, feel free to fork and open up a
branch to hackaway on. Ping either of us you want any feedback.

**Comment by toobulkeh** [comment]
So I was thinking developing just some bash scripts to move templates from the gem to the working directory files. Is that similar to what you had in mind or were you thinking of using a separate Ruby tool? (I'm not too familiar with this landscape, but willing to give it a shot).

I'd love to support any tool (not make it rails or middleman specific) and even other "languages" like coffeescript or haml -- though a simple html2haml would be enough for a first attempt.

**Comment by teoljungberg** [comment]
@toobulkeh I've been discussing with @Magnus-G to drop the gem support in total. Since, from what I understand, the biggest use of Refills is going onto the website and copy-paste the snippets from there. We're still not sure if this is a wise idea or not

**Comment by toobulkeh** [comment]
that would definitely be unfortunate. From a developer's perspective command line tools > GUI copy/pasting. For sure.

Just let me know if you decide to keep the gem! I'll be happy to discuss how I can help it get better.

**Comment by tysongach** [comment]
:+1: for _not_ dropping gem support, if possible.

I’m curious, @teoljungberg: What makes you want to drop support for it? Is it a maintenance issue, or hindering features in some way?

**Comment by teoljungberg** [comment]
It's mainly a maintenence issue, @magnus-g is the main maintainer of
Refills and is not the main user-type of the rubygem. I should probably
step in more and release new versions of the gem. @magnus-g and I can
sync that up.

But it if seems like the rubygems is widely used, we should continue
supporting it. I have a vague gutfeeling that it's actually not used
much

**Comment by Magnus-G** [comment]
@teoljungberg @toobulkeh yeah we really need someone in charge of the small parts of backend we have in this project! It's certainly outside of my frontend control.

**Comment by iDev0urer** [comment]
Just would like to say that I would plus 1 the heck out of this @teoljungberg. I just did a search for some way to use the refills gem with middleman and didn't find anything. For now I'll probably hardcode it in, but I can't wait to get some kind of generator out there.

**Comment by landed1** [comment]
I got here as I want to try something a little different and lighter for my NG App demo I am making than Bootstrap UI for Angular. My specific need was for a modal and refills has that. I am not sure what code to include and if I can include just the code for the modal. I like so far bourbon and neat but need a little bit more 'quick build' for things like modals that I should not have to develop and don't really want to either. Bower also gives the user an include problem that is solvable with the right path but at least it fits how a lot of us work. The gem stuff seems ok but now ruby and rails I don't want to learn another thing at least not yet.
I would be happy to know what file(s) to include to get rails components to work having bourbon and neat only (not sure I need bitters ?)
It might be just a case of needing a blogger to document an article to clear some things up and a use scenario rather than you needing to change to support bower. I am happy to copy and paste files where needed and prefer that to the gem stuff which feels a bit voodo - where did my files go etc...bloat....'bundle install' how does it now which one to install...rambling now...but I thought I would tip my hat to the nice work you guys are doing and I would like to continue with the product set.

**Comment by landed1** [comment]
I actually just copied the code given in the demo page and they work - with some base font styling that is normal it works without other downloading. So I can in fact simply modularly create all of these wonderful tools - and even take the modal js and make it angular directive and de-jquery it...
At least I think this is working....

**Comment by landed1** [comment]
I now have your refils modal working as an Angular directive - I will upload the repo as soon as I get it neater and ready.

**Comment by tysongach** [comment]
Closing for now, as we are working on a re-write of Refills with a new focus: https://github.com/thoughtbot/refills/projects
