### ISSUE TITLE
From Twitter: js classes?

### ISSUE THREAD

**Issue by Magnus-G** [thoughtbot/refills#234]
From [Twitter](https://twitter.com/marnen/status/559951979020292096):

> @bourbonsass is great, but js-* classes in Refills are silly. If .js-foo and .foo always appear together, that means they should be 1 class.

Marnen Laibow-Koser
‏@marnen

**Comment by marnen** [comment]
Wow, I wasn't even gonna raise this as an issue. Thanks for your attention!

Let me know if a more detailed explanation would be helpful.

**Comment by Magnus-G** [comment]
@marnen I think I know what you mean. But we wanted to separate the js-only classes and "calls" from the style classes. Your comment is valid though and I'd love to see an idea for a solution! A PR?

**Comment by marnen** [comment]
I actually think that the idea of separating "behavior" from "styling" classes is precisely the problem here. It's an artificial distinction and makes the markup less semantic to no benefit that I can see.

As an example, look at the sliding menu component at http://refills.bourbon.io/components/#er-toc-id-19. In particular, notice the following HTML: `<nav class="js-menu sliding-menu-content">`. Neither class is reused (or reusable) anywhere else. There's no reason that I can see to not just have the JS work on `$('.sliding-menu-content')`. The addition of the `js-menu` class just makes the markup more brittle (because you have to remember to include two classes, not just one) and less semantic: this DOM object is fundamentally one class, not two, and the markup shouldn't have to know whether the class is for behavior, styling, or both. 

Put another way, my fundamental objection to `js-*` classes is that I believe `class='sliding-menu-content'` means (semantically) "this is sliding menu content", not "this is styled/behaves in a particular way". And if it means "this is sliding menu content" -- that is, if it's a signifier of type -- then it's perfectly a appropriate for objects to look *and behave* differently based on the same signifier. Splitting it into two signifiers would only make sense if one or the other were independently reusable, which is not the case here as far as I can see. 

I'll turn the question around: what benefit do you see from separating behavior and styling classes? I really cannot think of any at all.

**Comment by marnen** [comment]
If you'd like a pull request with some of this in practice, I can try to write one.

**Comment by Magnus-G** [comment]
Our reasoning was that the style and the markup should be possible to tweak to the extent where the user might even want to change class names (e.g. for consistency reasons). Then he/she should be aware of which classes are used by `js` by seeing the `js-` prefix. 

What do you think about this discussion @kaishin @tysongach?

**Comment by marnen** [comment]
I'm not seeing how having two classes instead of one helps achieve the goal of making the code more tweakable. If anything, I think it makes it less so, because it breaks up one class artificially and forces the user to keep track of a dependency that should be in the code. Besides, the snippets are short enough that inspecting the JS to see which class names it uses is trivial.

**Comment by Magnus-G** [comment]
@marnen cool! I'd suggest sending a PR for one example file and we'll take it from there!

**Comment by marnen** [comment]
OK, I'll do that.

**Comment by Magnus-G** [comment]
@marnen closing this issue, awaiting the PR.

**Comment by marnen** [comment]
Coming. I got involved with other things. :)

**Comment by marnen** [comment]
Working on this now: picking a few simple examples. Note that the Modal component is already written this way.

**Comment by marnen** [comment]
See #245 for pull request. If time permits, I might add a few more examples.
