### ISSUE TITLE
Remove Variables

### ISSUE THREAD

**Issue by kaishin** [thoughtbot/refills#244]
I think variables in Refills are a premature optimization. We should leave it up to the user to refactor their code in the way that fits their project and context.

We claim that our tools try to stay away from the monolithic approach that other frameworks have taken, but the more I look at it the more I feel like we are going in the direction of more framework-ification.

I suggest we drop all variables from Refills components.

**Comment by Magnus-G** [comment]
I think this is an interesting approach.
However, one good thing about having variables is that they are interlinked and and a user can thus change just one color and have all the other colors follow, in a logical way. Would we completely skip that?

**Comment by kylefiedler** [comment]
+1 For me personally I usually delete all the variables and replace them with site specific ones. They've never really helped and usually hinder me. They add to what I believe is overhead to bringing in a Refill. It might not be as DRY from Refills standpoint but it lowers the bar for bringing in one or two Refills to the site and makes each Refill a little less complex.

**Comment by Magnus-G** [comment]
@kylefiedler cool, I see what you mean. Would you (as an example) say it's best to specify `line-height: 1.5;` in each and every component that contains copy? Something you might have to tweak later on? This would also apply for `$base-spacing` and `$small-spacing` where we'd secify 1.5em and 1em for spaces in the components. 

The minimalist alternative would be to not define these at all, but I think we'd lose a lot of users if we "let the components be ugly". I.e. let text blocks be all crammed, and no paddings etc.

**Comment by kylefiedler** [comment]
@Magnus-G I think styles shouldn't be set in the Refill unless it's absolutely needed. In your `line-hight` example it would be one of the things I would remove because I'd want it to fall back to the inherit `line-height` consistent with the rest of the site I'm building. This is assuming that `line-height` isn't needed for the component to work. Things like padding and margin I'm probably going to change so I don't care as much if they are already there. 

This is all coming from my perspective. There have been times when I could have used a Refill but I chose not to because I felt like I'd have to delete/change so much that it was easier to just write it myself. I also care more about building a tool that is useful for us than has a lot of users.

**Comment by tysongach** [comment]
+1 for not defining things like line-height. Those should be inherited in most cases. Refills should be mostly non-styled and just be a “components”. It's a thing with some HTML structure, a little layout styles and maybe some JavaScript. Most Refills are over-the-top and very opinionated, therefore 95% of the time they don’t fit into any project.

**Comment by Magnus-G** [comment]
@tysongach It'd be great to see a PR for just one pattern to understand how you'd like to have it. Accordion-tabs is a good one to try out. Would you be able to do that?

If I remove all the usage of variables in that one it ends up looking like this, and that's pretty useless I think:

![image](https://cloud.githubusercontent.com/assets/2095625/6129406/a0b874fc-b13e-11e4-9487-3ac1732ca131.png)

![image](https://cloud.githubusercontent.com/assets/2095625/6129412/aefcbf00-b13e-11e4-9ca5-94cd8596cf47.png)

I don't see a big point in using a `background-color` or a `padding` or a specified action color for any component/pattern if they are going to be set globally, since the user would still have to go in and scrape those out.

**Comment by kylefiedler** [comment]
@Magnus-G I honestly think that that is more useful to me. It takes the same stance as Bitters where it gives me all the control to style them and not have to worry about any overhead of removing styles.

**Comment by tysongach** [comment]
Yeah, I realize it doesn’t _look_ pretty, but I'm more after the structure than the visual style. Visual style is *highly* dependent on the project and the designer(s) involved. It can't be expected that the visual style of Refills will always match those of the project.

**Comment by Magnus-G** [comment]
In the unstyled example we don't even see which tab is highlighted. That depends on applying a style to the highlighted item and I feel like that should be a minimum for the actual pattern.

I'm not super worried about things looking "ugly" as much as the fact that we'll lose subtle "design helps" such as "this corner is rounded in this mode but not in this one" etc. Look at "another tab" below (and I'm not saying corners **should** be rounded. There are other types of examples too)

![image](https://cloud.githubusercontent.com/assets/2095625/6130031/d70fac9c-b142-11e4-894c-84327c053160.png)

![image](https://cloud.githubusercontent.com/assets/2095625/6130039/e538d9e2-b142-11e4-92e1-5d2c93937c22.png)

**Comment by Magnus-G** [comment]
This PR idea becomes relevant again: https://github.com/thoughtbot/refills/pull/225

**Comment by Magnus-G** [comment]
@kylefiedler Try out https://refills-staging.herokuapp.com/ and see if it's the right direction.

**Comment by kylefiedler** [comment]
Yea that to me is more along the lines of what I want. Some of them are still components (Cards, Comments) that I wouldn't use because I think I could write them faster than copying and pasting. Or I'm not sure that I would think of them as a component in Refills. I want Refills for things like sticky navigation, tabs, dropdowns, navigation that goes to a menu at mobile, modal window. These are things that I do on almost every project but it's a pain for me to have to write or find the javascript and styles to do those things. 

This is all from my personal perspective; it might not be the right direction for Refills.

**Comment by Magnus-G** [comment]
@kylefiedler great! Yeah I also think this is a step in the right direction. However, I think this is a separate project. Refills are semi-styled components for people who want to pick up something "ready" and tweak it. 

This is a minimalist, unstyled component library. I'd like to introduce it as a library of its own and see how it stands up to Refills. Which one we'll use more, which one people will prefer.

Nice detail: You can toggle Bitters on or off for this library and it will pick up the Bitters styles in a nice way, without Bitters being a dependency.

**Comment by Magnus-G** [comment]
Closing this.
