### ISSUE TITLE
Adding sass syntax to the "show code"

### ISSUE THREAD

**Issue by labo-css** [thoughtbot/refills#292]
Self explanatory title, this would be a great addition.
Maybe jade lang for the html too, if this not too much.

Thanx a lot for the great tools you made, btw.

**Comment by Magnus-G** [comment]
This could be done in the same way we currently copy coffee script instead of javascript. I'm not sure how nice and clean the Sass would be though, if we just generate it from the SCSS or the CSS. I don't think we'll be able to maintain Refills if we have to create the Sass manually unfortunately.

**Comment by labo-css** [comment]
Sass does not provide a cli for that? I don't know how it can be implemented in this case.

**Comment by teoljungberg** [comment]
Currently we ad-hoc generate coffeescript from javascript in a Rake task, the sad thing there is that we have to remember to do that(it's not automated, but that can be changed). We could do that for CSS/SCSS aswell, but then I would suggest that we have to rewrite the CSS code to be SCSS. Since it's easier compiler-wise to generate CSS from SCSS since SCSS is the pre-processor. 

/cc @Magnus-G

**Comment by tysongach** [comment]
Closing for now. We had a [similar suggestion over on Bitters](https://github.com/thoughtbot/bitters/pull/138), but ultimately I’m not sure there’s a lot of demand for this to introduce complexity into the code.
