### ISSUE TITLE
Refills in Middleman

### ISSUE THREAD

**Issue by aaromnido** [thoughtbot/refills#306]
Hi guys,
Congrats!! Pretty awesome work with refills!!

My question is: How I can use Refills into a Middleman Project?
I tried to ad a gem 'refills' and next install refills into my /stylsheets/ folder, but install doesn't works in this case.

**Comment by joshuaogle** [comment]
Hi Fernando! Unfortunately the gem isn't going to work since it's a Rails generator. There has been [some discussion](https://github.com/thoughtbot/refills/issues/227) on how to package Refills for other things like MIddleman, but while it doesn't work as easily right now, it is something we want to solve. I would really like to get Refills into [our Middleman starter kit](https://github.com/thoughtbot/proteus-middleman) as well.

For now, we've been copying the components from the [Refills site](http://refills.bourbon.io) into our projects. It's not nearly as streamlined, I know.

If you have ideas for how you'd like to see it work for things like Middleman, feel free to drop a comment in #227

**Comment by aaromnido** [comment]
No problem. I can use Refills by the copy/paste way.
Thanks for your answer!! :)
