### ISSUE TITLE
refills UI kit (for designers)

### ISSUE THREAD

**Issue by onlyjamie** [thoughtbot/refills#313]
Hi all, I was wondering if anyone had made a UI kit (.psd/.sketch) for Refills? I was going to start making a few elements for a project but I figured I'd ask in case anyone had something started or would like to collaborate on making one.

**Comment by Magnus-G** [comment]
@onlyjamie there is no such thing as far as I know. I think any UI kit could be used though, since the Refills components are meant to be generic and should be tweaked to fit the design we're working on.

If you still feel like this is something that should exist, please go ahead and build it! I'm sure it could come in handy!

**Comment by Magnus-G** [comment]
Closing this for now
