### ISSUE TITLE
Multiple Vertical Tabs on a page doesn't work

### ISSUE THREAD

**Issue by MikeHarrison** [thoughtbot/refills#352]
Hi,

These refills are awesome! Hit one issue - more than one set of vertical tabs (http://refills.bourbon.io/unstyled/#er-toc-id-17) on a page isn't working properly - only the content of the first set is being shown.

**Comment by Magnus-G** [comment]
@MikeHarrison I think this might be because the `js` is calling specific classes and if you just copy paste an extra vertical tabs component without calling it (and the js that it uses) something else, you will target the same component.

does it work better if you copy paste it and then for the other instance of it try and add `-2` or something to the ending of all the class names in the second one? important to add this for all the js-code to to make it work.

ideally you should use the same `js` for counting all of the instances in. for that you might have to use `return` or such, but in order to just make it work you could try changing names like so:

```
$(".js-vertical-tab-2").click(function(event) {
  event.preventDefault();

  $(".js-vertical-tab-content-2").hide();
  var activeTab = $(this).attr("rel");
  $("#"+activeTab).show();

  $(".js-vertical-tab-2").removeClass("is-active");
  $(this).addClass("is-active");
```

**Comment by MikeHarrison** [comment]
HI Magnus,

Thanks for the help. I ended up with the below, which still requires specific id's but makes it a bit more re-usable:

```
$(".js-vertical-tab-content").hide();
$(".js-vertical-tab-content:first-of-type").show();

/* if in tab mode */
$(".js-vertical-tab").click(function(event) {
  event.preventDefault();

  var activeTab = $(this).attr("rel");
  $currentTab = $("#"+activeTab);
  $currentTab.parent().find('.js-vertical-tab-content').hide();
  $currentTab.show();

  $(".js-vertical-tab").removeClass("is-active");
  $(this).addClass("is-active");

  $(".js-vertical-tab-accordion-heading").removeClass("is-active");
  $(".js-vertical-tab-accordion-heading[rel^='"+activeTab+"']").addClass("is-active");
});

/* if in accordion mode */
$(".js-vertical-tab-accordion-heading").click(function(event) {
  event.preventDefault();

  var activeTab = $(this).attr("rel");
  $currentTab = $("#"+activeTab);
  $currentTab.parent().find('.js-vertical-tab-content').hide();
  $currentTab.show();

  $(".js-vertical-tab-accordion-heading").removeClass("is-active");
  $(this).addClass("is-active");

  $(".js-vertical-tab").removeClass("is-active");
  $(".js-vertical-tab[rel^='"+accordionActiveTab+"']").addClass("is-active");
});
```

I am looking at possibly converting the refill into a plugin to avoid the issue

**Comment by tysongach** [comment]
I’m closing this as we are focusing our efforts on a [new, rewritten Refills library](https://github.com/thoughtbot/refills/projects) with a focus on accessibility and removal of grid and visual opinion for components. You can see a preview of the work here: http://refills.netlify.com/

Existing components and patterns from the 0.2.0 release will be provided as-is (no longer maintained) until the new version is released.
