### ISSUE TITLE
neat 2.0?

### ISSUE THREAD

**Issue by afm-sayem** [thoughtbot/refills#400]
bourbon: `5.0beta-6`
neat: `2.0beta-1`
bitters: `1.4`

I'm using node-sass. I just updated to bourbon 5.0beta and neat 5.0beta and some components stopped working with following:
`Error: no mixin named media`

Seems like there's no mixin called media [in neat 2.0](http://thoughtbot.github.io/neat-docs/2-0-0-beta-1)

Any migration guide to move current components to neat 2.0 will be very helpful. Also, I saw that refills have been updated to support bourbon 5.0, is there any immediate plan to port the components to neat 2.0?

**Comment by whmii** [comment]
Hi @afm-sayem 
Since most of the components would need to be rewritten, Refills does not currently support Neat 2.0. It would be best to stick to 1.8.

This will likely change once neat 2.0 is a bit closer to coming out of beta. If we were to do a wholesale update, we would need a way of tying together the "use X version of neat with X version of refils, etc, etc…". cc: @brendastorer

**Comment by jondkinney** [comment]
Any update on getting refills up to snuff with Neat 2.0? Suspenders now uses both refills and neat 2.0 (beta) and things work when bootstrapping a new project because it only uses the flashes refill, but if you try to pull in the navigation refill it blows up with the error @afm-sayem mentioned. I downgraded my fork of suspenders (with customizations) to use neat 1.8 for now as suggested by @whmii, but having an updated refills for neat 2.0 would be mo bedda! Happy to help, if feasible. LMK. Thanks!

**Comment by whmii** [comment]
@jondkinney This is more be more of a refills issue, would you mind crossposting this to https://github.com/thoughtbot/refills/issues

**Comment by whmii** [comment]
deleted My comment. thought I was in another project.

**Comment by spkellydev** [comment]
Any word on when Refills is going to support Neat 2.0?
