### ISSUE TITLE
Any Navigation Refills?

### ISSUE THREAD

**Issue by bgarrant** [thoughtbot/refills#435]
I know you are all working on a new Refills to work with latest Neat and Bourbon, but do you have any plans for a Navigation Refill like you had previously?  I am using the latest versions of Neat and Bourbon 4.3.3 and I am searching for a navbar component like you had before.  Do you have anything that will work with latest versions, or can you advise how to make the old one work?  It seems it is just missing a couple variables like ` $horizontal-bar-mode:`.

http://refills.bourbon.io/#er-toc-id-13

**Comment by creuter** [comment]
We aren't currently planning to rebuild the navigation refill. We'll instead be focusing on smaller components that aren't so opinionated about how they're composed.

In the linked scss, `$horizontal-bar-mode` is defined as `$large-screen`, which is defined above that as `$large-screen: 53.75em !default;`. So those variables are there, and that doesn't appear to the problem.

It's more likely that you don't have the `media` function since upgrading your version of Neat. You can instead use the normal syntax for a media query:

```css
@media screen and (min-width: $horizontal-bar-mode) {
  ...
}
```

or you could dig use the new [grid-media](http://neat.bourbon.io/docs/latest#grid-media) function in Neat 2.0.0.

The next version of Refills will no longer depend on Neat, to remove these types of inconsistencies.

**Comment by bgarrant** [comment]
Sounds great.  I will try that.  Thanks.

**Comment by bgarrant** [comment]
Is there anything wrong with using that navigation refill as far as functions or browser compatibility?  Just curious before I use it.

**Comment by creuter** [comment]
A lot of the implementation details could be argued, but the resulting markup and styling are fine, and should work in all modern browsers.

**Comment by bgarrant** [comment]
Thanks so much.  Do you have any other suggestions of a more up-to-date responsive navigation script with dropdowns?  Anything you can suggest?
